# Generated by Django 4.2.2 on 2023-07-31 08:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imageUrl', models.ImageField(upload_to='')),
                ('countryOfOrigin', models.CharField(max_length=255)),
                ('typicalMealTime', models.IntegerField(verbose_name=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')])),
                ('dateAdded', models.DateTimeField(default=datetime.datetime(2023, 7, 31, 17, 48, 9, 140845))),
            ],
        ),
        migrations.CreateModel(
            name='MealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('dateOfRating', models.DateTimeField(default=datetime.datetime(2023, 7, 31, 17, 48, 9, 187718))),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
        ),
    ]
