# Generated by Django 4.2.2 on 2023-08-16 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='dateAdded',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 10, 40, 4, 872855)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='imageUrl',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='typicalMealTime',
            field=models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')]),
        ),
        migrations.AlterField(
            model_name='mealrating',
            name='dateOfRating',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 10, 40, 4, 893417)),
        ),
    ]
