# Generated by Django 4.2.2 on 2023-08-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal_slug_alter_meal_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mealrating',
            name='dateOfRating',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
